name: jadwalperawatanmesin
description: "A new Flutter project."

publish_to: 'none' # Jangan publish ke pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Kalau mau pakai gambar, aktifkan baris ini:
  # assets:
  #   - assets/images/

  # Kalau mau pakai custom font, aktifkan contoh di bawah:
  # fonts:
  #   - family: MyFont
  #     fonts:
  #       - asset: fonts/MyFont-Regular.ttf
  #       - asset: fonts/MyFont-Bold.ttf